"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

export default function ReportPage() {
  const router = useRouter();
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(true);
  const [rating, setRating] = useState(null);
  const [userMeta, setUserMeta] = useState(null);

  useEffect(() => {
    const isPaid = localStorage.getItem("isPaid");
    if (isPaid !== "true") {
      router.push("/preview");
      return;
    }

    const raw = localStorage.getItem("palmFeatures");
    if (!raw || raw === "[object Object]") {
      setReport("Palm data corrupted. Please upload again.");
      setLoading(false);
      return;
    }

    const features = JSON.parse(raw);

    setUserMeta({
      age: features.age || "N/A",
      gender: features.gender || "N/A",
      language:
        (localStorage.getItem("reportLanguage") || "hinglish") === "english"
          ? "English"
          : "Hinglish",
    });

    const language = localStorage.getItem("reportLanguage") || "hinglish";

    fetch("/api/generate-report", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ features, language }),
    })
      .then((res) => res.json())
      .then((data) => {
        setReport(data.report || "Unable to generate report.");
        setLoading(false);
      });

    const savedRating = localStorage.getItem("lastRating");
    if (savedRating) setRating(parseInt(savedRating));
  }, []);

  const downloadPDF = async () => {
    const element = document.getElementById("report-content");

    const canvas = await html2canvas(element, {
      scale: 2,
      backgroundColor: "#000000",
    });

    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "pt", "a4");

    const imgWidth = 595;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);

    pdf.save("PalmMitra-Career-Paisa-Report.pdf");
  };

  return (
    <main className="min-h-screen bg-gradient-to-b from-[#0f0f0f] to-black text-white px-4 py-10">
      <div className="max-w-3xl mx-auto bg-white/5 border border-white/10 rounded-2xl p-8 shadow-2xl">

        {/* HEADER */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
          <div>
            <h1 className="text-3xl font-bold bg-gradient-to-r from-amber-300 to-amber-500 bg-clip-text text-transparent">
              Your Personal Career & Paisa Blueprint
            </h1>

            <p className="text-sm opacity-70 mt-1">
              AI-powered clarity based on your palm patterns
            </p>
          </div>

          <span className="inline-block px-3 py-1 text-xs rounded-lg bg-amber-400/10 text-amber-300 border border-amber-400/20">
            PREMIUM ANALYSIS
          </span>
        </div>

        {/* USER PERSONALIZATION CARD */}
        {userMeta && (
          <div className="mt-6 bg-white/5 border border-white/10 rounded-xl p-4 text-sm">
            <p className="font-semibold mb-2 text-amber-300">
              Report Generated For
            </p>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-2 opacity-80">
              <div>Age: {userMeta.age}</div>
              <div>Gender: {userMeta.gender}</div>
              <div>Language: {userMeta.language}</div>
            </div>
          </div>
        )}

        {loading ? (
          <p className="opacity-80 mt-8">Analyzing palm patterns...</p>
        ) : (
          <>
            {/* MAIN REPORT CONTAINER */}
            <div
              id="report-content"
              className="mt-8 leading-relaxed text-[15px] bg-white/5 border border-white/10 p-6 rounded-xl"
            >
              <div className="flex items-center gap-2 mb-4">
                <h2 className="text-xl font-bold text-amber-400">
                  PalmMitra – Career & Paisa Report
                </h2>
              </div>

              <div className="whitespace-pre-wrap">
                {report}
              </div>

              <div className="mt-6 pt-3 border-t border-white/10">
                <p className="text-xs opacity-60">
                  Generated by PalmMitra | AI-based directional guidance
                </p>
              </div>
            </div>

            {/* REFLECTION CARD */}
            <div className="mt-8 p-5 rounded-xl bg-white/10 border border-amber-400/20 text-sm">
              <strong className="block mb-1 text-amber-300">
                Pause & Reflect
              </strong>
              <p>
                Agle 90 din mein kaunsa ek decision hai jahan aap consciously  
                stability vs growth choose karoge?
              </p>
            </div>

            {/* ACTION BUTTONS */}
            <div className="mt-8 flex flex-wrap gap-3">
              <button
                onClick={downloadPDF}
                className="px-6 py-3 rounded-xl bg-gradient-to-r from-amber-300 to-amber-500 text-black font-bold hover:scale-[1.02] transition-all"
              >
                Download PDF
              </button>

              <button
                onClick={() => navigator.clipboard.writeText(report)}
                className="px-4 py-3 rounded-xl bg-white/10 border border-white/10 text-sm hover:bg-white/20 transition-all"
              >
                Copy Report
              </button>

              <button
                onClick={() =>
                  navigator.share?.({
                    title: "My PalmMitra Report",
                    text: report.slice(0, 200) + "...",
                    url: window.location.href,
                  })
                }
                className="px-4 py-3 rounded-xl bg-white/10 border border-white/10 text-sm hover:bg-white/20 transition-all"
              >
                Share Report
              </button>
            </div>

            {/* RATING SYSTEM */}
            <div className="mt-10 p-5 rounded-xl bg-white/5 border border-white/10">
              <p className="text-sm opacity-80 mb-3">
                Kya yeh report aapko useful lagi?
              </p>

              <div className="flex gap-2 flex-wrap">
                {[1, 2, 3, 4, 5].map((num) => (
                  <button
                    key={num}
                    onClick={() => {
                      setRating(num);
                      localStorage.setItem("lastRating", num);
                    }}
                    className={`px-3 py-2 rounded-lg border transition-all ${
                      rating === num
                        ? "bg-amber-400 text-black"
                        : "bg-white/5 border-white/10 hover:bg-white/10"
                    }`}
                  >
                    {num}
                  </button>
                ))}
              </div>

              {rating && (
                <p className="mt-3 text-xs opacity-70">
                  Thanks! Aapka feedback PalmMitra ko better banata hai.
                </p>
              )}
            </div>
          </>
        )}

        {/* FOOTER DISCLAIMER */}
        <div className="mt-10 pt-5 border-t border-white/10 text-xs opacity-50 leading-relaxed">
          This report is designed to give clarity, not certainty. PalmMitra does
          not make guarantees or predictions. Decisions should be taken with
          personal judgment and real-world context.
        </div>

      </div>
    </main>
  );
}
