"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

export default function ReportPage() {
  const router = useRouter();
  const [report, setReport] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const isPaid = localStorage.getItem("isPaid");
    if (isPaid !== "true") {
      router.push("/preview");
      return;
    }

    const raw = localStorage.getItem("palmFeatures");
    if (!raw || raw === "[object Object]") {
      setReport("Palm data corrupted. Please upload again.");
      setLoading(false);
      return;
    }

    const features = JSON.parse(raw);

    fetch("/api/generate-report", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ features }),
    })
      .then((res) => res.json())
      .then((data) => {
        setReport(data.report || "Unable to generate report.");
        setLoading(false);
      });
  }, []);

const downloadPDF = async () => {
  const element = document.getElementById("report-content");

  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: "#000000",
  });

  const imgData = canvas.toDataURL("image/png");

  const pdf = new jsPDF("p", "pt", "a4");

  const imgWidth = 595;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);

  pdf.save("PalmMitra-Career-Paisa-Report.pdf");
};


  return (
    <main className="min-h-screen bg-gradient-to-b from-[#0f0f0f] to-black text-white px-4 py-10">
      <div className="max-w-3xl mx-auto bg-white/5 border border-white/10 rounded-2xl p-8 shadow-2xl">

        <h1 className="text-3xl font-bold bg-gradient-to-r from-amber-300 to-amber-500 bg-clip-text text-transparent">
          Your Career & Paisa Report
        </h1>

        <p className="text-sm opacity-70 mt-1">
          Based on your uploaded palm
        </p>

        <p className="text-sm opacity-60 mt-4">
          Generated using visible palm observations and AI-based interpretation.
        </p>

        {loading ? (
          <p className="opacity-80 mt-8">Analyzing palm patterns...</p>
        ) : (
          <>
<div
  id="report-content"
  className="mt-8 whitespace-pre-wrap leading-relaxed text-[15px] bg-white/5 border border-white/10 p-6 rounded-xl"
>
  <h2 className="text-xl font-bold mb-4 text-amber-400">
    PalmMitra – Career & Paisa Report
  </h2>

  {report}

  <p className="mt-6 text-xs opacity-60">
    Generated by PalmMitra | AI-based directional guidance
  </p>
</div>


            <div className="mt-8 p-5 rounded-xl bg-white/5 border border-white/10 text-sm opacity-90">
              <strong className="block mb-1">💭 Think about this:</strong>
              <p>
                Agle 90 din mein kaunsa ek decision hai jahan aap consciously  
                stability vs growth choose karoge?
              </p>
            </div>

            <button
              onClick={downloadPDF}
              className="mt-8 px-6 py-3 rounded-xl bg-gradient-to-r from-amber-300 to-amber-500 text-black font-bold hover:scale-[1.02] transition-all"
            >
              Download PDF
            </button>
          </>
        )}

        <div className="mt-10 pt-5 border-t border-white/10 text-xs opacity-50 leading-relaxed">
          This report is designed to give clarity, not certainty. PalmMitra does
          not make guarantees or predictions. Decisions should be taken with
          personal judgment and real-world context.
        </div>

      </div>
    </main>
  );
}
